### ISSUE TITLE
Test case 4: Verifying the file can be opened - unsuccessful 

### ISSUE THREAD

**Issue by jordan937** [sopmill/webScrapper#10]
Test case to see if ai summary is 50 words or more.

**Comment by sopmill** [comment]
Test case-4: Verifying the file is not open with a non-existent file. 
Location: webScrapper/project_04/module_1/function_01.py . Lines: 34-37.

I am done with this test case. Please review it and close the issue.

**Comment by jordan937** [comment]
it's been reviewed.
