### ISSUE TITLE
Test Case 8:  Network Error

### ISSUE THREAD

**Issue by sopmill** [sopmill/webScrapper#8]
This test simulates a scenario where there is a network error, such as the domain not existing.

**Comment by jordan937** [comment]
I am done with the code please review it then close the issue.
Test case-8: check output for Network error. Location: module_2/function_02.py . Lines: 51-53.

**Comment by sopmill** [comment]
The lines for this test case are 34-53, not just 51-53. Correct?

**Comment by sopmill** [comment]
It has been reviewed.
